# Header

menu:
  最新文章: /
  历史归档: /archives
  我的读书: /books
  我的电影: /movies
  我的游戏: /games
  发现大佬: /social
  关于自己: /about
  百度统计: /statistics

# SubNav
subnav:
  github: "https://github.com/mythsman"
  weibo: "http://weibo.com/u/5320278224"
  rss: "/atom.xml"
  zhihu: "https://www.zhihu.com/people/ding-qing-zhu/"
  qq: "https://user.qzone.qq.com/1276077732"
  #weixin: "#"
  jianshu: "http://www.jianshu.com/users/51a5769033f1/"
  douban: "https://www.douban.com/people/mythsman/"
  segmentfault: "https://segmentfault.com/u/mythsman"
  bilibili: "http://space.bilibili.com/101787792"
  #acfun: "#"
  mail: "mailto:dqz48548263@qq.com"
  #facebook: "#"
  google: "https://plus.google.com/u/0/102714669152385773121"
  #twitter: "#"
  #linkedin: "#"

rss: /atom.xml

# 是否需要修改 root 路径
# 如果您的网站存放在子目录中，例如 http://yoursite.com/blog，
# 请将您的 url 设为 http://yoursite.com/blog 并把 root 设为 /blog/。
root: 

# Content

# 文章太长，截断按钮文字
excerpt_link: more
# 文章卡片右下角常驻链接，不需要请设置为false
show_all_link: '展开全文'
# 数学公式
mathjax: true
# 是否在新窗口打开链接
open_in_new: false

# 打赏
# 请在需要打赏的文章的md文件头部，设置属性reward: true

# 打赏基础设定：0-关闭打赏； 1-文章对应的md文件里有reward:true属性，才有打赏； 2-所有文章均有打赏
reward_type: 2
# 打赏wording
reward_wording: '欢迎留言^.^'
# 支付宝二维码图片地址，跟你设置头像的方式一样。比如：/assets/img/alipay.jpg
# HTTPS://QR.ALIPAY.COM/FKX03362WLRQXYEJURYO90
alipay: /images/alipay.png
# 微信二维码图片地址
# wxp://f2f0aKXwAfPrGOVnFTjyYS27CcdourkeCgyX
weixin: /images/weixin.png


# 目录
# 目录设定：0-不显示目录； 1-文章对应的md文件里有toc:true属性，才有目录； 2-所有文章均显示目录
toc: 2
# 根据自己的习惯来设置，如果你的目录标题习惯有标号，置为true即可隐藏hexo重复的序号；否则置为false
toc_hide_index: true
# 目录为空时的提示
toc_empty_wording: '本文没有目录'

# 是否有快速回到顶部的按钮
top: true

# Miscellaneous
baidu_analytics: '4fe809868242dc9d16990780f04b2a56'
#google_analytics: 'UA-99608806-1'
favicon: /favicon.ico

#你的头像url
avatar: /images/avatar.png

#是否开启分享
share_jia: false

#评论：1、多说；2、网易云跟帖；3、畅言；4、Disqus 不需要使用某项，直接设置值为false，或注释掉
#具体请参考wiki：https://github.com/litten/hexo-theme-yilia/wiki/

#1、多说
duoshuo: false

#2、网易云跟帖
wangyiyun: false

#3、畅言
changyan_appid: cyt3JyjBy
changyan_conf: prod_18351297baa5595579646e41117c6b43

#4、Disqus 在hexo根目录的config里也有disqus_shortname字段，优先使用yilia的
disqus: false

# 样式定制 - 一般不需要修改，除非有很强的定制欲望…
style:
  # 头像上面的背景颜色
  header: '#84C1FF'
  #header: '#4d4d4d'
  # 右滑板块背景
  #slider: 'linear-gradient(200deg,#a0cfe4,#e8c37e)'
  slider: 'linear-gradient(100deg,#b0dfe4,#48432e)'

# slider的设置
slider:
  # 是否默认展开tags板块
  showTags: true


# 智能菜单
# 如不需要，将该对应项置为false
# 比如
#smart_menu:
#  friends: false
smart_menu:
  innerArchive: 搜索
  friends: 朋友
  aboutme: 说明

friends:
  Mikito: http://mikito.cn
  Ivy_end: http://www.ivy-end.com
  sdwalker: http://www.sdwalker.com
  Maomorn: http://maomorn.cn/wordpress
  Anthony_An: http://blog.ibilidi.cn
  Huas: http://qyxhsj.com.cn
  AngelMsger: https://angelmsger.com
  Netrvin: https://131.re
  ihoeys: https://blog.ihoey.com
  callouweicheng: http://blog.callouweicheng.cn
  Decader_Luo: http://decader.cn/
  ZheWang: http://zhewangchina.cn
  Paladnix: https://paladnix.github.io
  Dcc: https://dcc.cat
  泛泛而谈: https://tomato_peach.coding.me
  Liuye: https://liuyehcf.github.io
  HarrySheep: https://harrysheep.github.io
  Alliot: https://www.iots.vip
  白吟灵: https://whiteyin.github.io

aboutme: <span>本站点创建于2015年11月，采用<a href="https://hexo.io/" target="_blank">Hexo</a>开源框架，在<a href="https://github.com/litten/hexo-theme-yilia" target="_blank">yilia</a>主题基础上进行修改，加入<a href="https://github.com/mythsman/hexo-douban" target="_blank">豆瓣插件</a>同步读书电影信息，引入百度统计页面，用畅言插件做评论系统，全站采用https协议，静态文件部署在阿里云VPS上，，<a href="https://github.com/jupyter/notebook" target="_blank">Jupyter</a>作为Web端后台以及在线编辑器，并用Nginx做二级域名映射，网站源码以及文章托管于<a href="https://github.com/mythsman/blog" target="_blank">GITHUB</a>，所有文章都可以在GITHUB上找到markdown原文，欢迎大家互相交流学习。</span>
